version: '3'
services:
  nodejs:
    build: ./nodejs
    container_name: "nodejs"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db